build:
  maxIssues: 0

complexity:
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 8

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
